### ISSUE TITLE
Clean up command handler

### ISSUE THREAD

**Issue by zeffo** [rachit1601/Re-Dcrypt-Bot#6]
Use ext.commands, will look and perform better than the command handler you have now

**Comment by Warhawk947** [comment]
ok, will look into it!

**Comment by rachit1601** [comment]
> Use ext.commands, will look and perform better than the command handler you have now

Ya I know that but I'm more comfortable in python & currently, I don't have the time to learn something else due to my exams. 
Hence I stuck with the client instead of the bot. The client's format is almost like python.

**Comment by zeffo** [comment]
ext.commands is a part of the discord.py module. It's also very easy to use!
Here is a nice guide: https://vcokltfre.dev

Good luck with the Bot Jam!

**Comment by Warhawk947** [comment]
thank you!

**Comment by rachit1601** [comment]
> ext.commands is a part of the discord.py module. It's also very easy to use!
> Here is a nice guide: https://vcokltfre.dev
> 
> Good luck with the Bot Jam!

Ohh thanks for the guide. & Regarding the bot Jam. I discovered that quite some days after I made the bot & hence submitted it. Initially, I had no intention to participate. I discovered the bot jam while making things for my bot 😅
